texts = [
    "I was charged twice",
    "I was charged for something I did not purchase",
    "My payment failed",
    "I cannot update my card",
    "Why is my invoice higher than usual",
    "I need a refund for my last order",
    "My subscription renewed but I wanted to cancel",
    "Can you explain this extra charge on my bill",
    "I was billed after I cancelled my plan",
    "My credit card was declined",
    "I want to switch to a different payment method",
    "How do I download my past invoices",
    "I was charged in the wrong currency",
    "There is a duplicate transaction on my account",
    "I never received a receipt for my purchase",
    "Can I get a discount applied to my next bill",
    "My free trial ended and I was charged unexpectedly",
    "I need to update my billing address",
    "The coupon code did not apply to my order",
    "I want to change my subscription plan",
    "Why was I charged a late fee",
    "I need an itemized breakdown of my charges",
    "My payment is stuck in pending status",
    "Can I pay with PayPal instead of a card",
    "I was overcharged for my subscription",
    "How do I cancel automatic renewal",
    "I want a refund because I was double billed",
    "My gift card balance is not showing correctly",
    "I need to update my company's tax ID for invoices",
    "The price I was charged does not match the listing",
    "I am being charged for a service I never used",
    "Can you remove a card from my account",
    "I want to downgrade my plan to save money",
    "My bank flagged a charge from your company",
    "How do I set up a payment plan",
    "I need proof of payment for reimbursement",
    "Why did my subscription price increase",
    "I cancelled but still see a pending charge",
    "Can I split my payment across two cards",
    "My promo credit was not applied to my invoice",
    "I want to dispute a charge on my account",
    "How do I add a new credit card to my account",
    "I was charged an annual fee I did not expect",
    "Can you send me a copy of my receipt",
    "My currency conversion fee seems too high",
    "I need to update the expiration date on my card",
    "Why does my invoice show two charges for one month",
    "I want to know when my next payment is due",
    "I was charged for a plan upgrade I did not request",
    "Can I get a refund for an unused subscription period",
    "The website keeps crashing",
    "The application is showing an error",
    "The page is not loading",
    "The server is down",
    "I cannot upload files to the platform",
    "The app freezes every time I open it",
    "I am getting a 404 error on the homepage",
    "My dashboard is not displaying any data",
    "The mobile app crashes on startup",
    "I keep getting a timeout error",
    "The search feature is not returning results",
    "Images are not loading on the site",
    "The checkout page is broken",
    "I cannot download my report",
    "The app is running extremely slowly",
    "I am seeing a blank screen after login",
    "The API is returning errors",
    "My changes are not saving",
    "The video will not play",
    "I get an error message when submitting the form",
    "The site is stuck loading forever",
    "My integration stopped syncing data",
    "The button on the page does not respond",
    "I cannot connect to the server",
    "The export feature is not working",
    "I am getting a security certificate warning",
    "The notifications are not showing up",
    "My files got corrupted after uploading",
    "The system logged me out unexpectedly",
    "I cannot access the settings page",
    "The app shows outdated information",
    "There is a bug in the calendar feature",
    "The chat widget is not loading",
    "I am experiencing constant lag in the app",
    "The print function is not working",
    "My data disappeared after an update",
    "The app is not compatible with my device",
    "I cannot sync my account across devices",
    "The website layout looks broken on mobile",
    "I am getting a database connection error",
    "The software keeps crashing during setup",
    "My widget is displaying the wrong data",
    "The app update caused new errors",
    "I cannot install the latest version",
    "The link I clicked leads to an error page",
    "The system is not recognizing my input",
    "My session keeps expiring too quickly",
    "The map feature is not loading properly",
    "I am unable to attach files to a ticket",
    "The dashboard graphs are not rendering",
    "I forgot my password",
    "I cannot login to my account",
    "I want to change my email",
    "I cannot reset my password",
    "How do I delete my account",
    "I need to update my profile information",
    "My account got locked out",
    "I want to change my username",
    "I did not receive the verification email",
    "How do I enable two factor authentication",
    "My account was suspended and I do not know why",
    "I want to merge two accounts into one",
    "I cannot verify my phone number",
    "How do I change my account password",
    "My account shows the wrong name",
    "I want to update my shipping address",
    "I cannot access my account settings",
    "How do I recover a deactivated account",
    "I never received my account activation link",
    "I want to change my security questions",
    "My login keeps failing even with the correct password",
    "How do I unlink my social media login",
    "I need to update my date of birth on file",
    "My account was hacked and I need help",
    "How do I add a family member to my account",
    "I want to disable two factor authentication",
    "My profile picture will not update",
    "I cannot find my account after signing up",
    "How do I change my notification preferences",
    "I want to permanently close my account",
    "My email address bounced during signup",
    "I need help transferring my account to a new owner",
    "How do I check my login history",
    "My account is showing incorrect membership status",
    "I want to change the language on my account",
    "I cannot update my emergency contact information",
    "How do I revoke access for a connected app",
    "My account is stuck in a pending verification state",
    "I want to reactivate my old account",
    "How do I change my privacy settings",
    "I cannot remove an old phone number from my account",
    "My account got flagged for suspicious activity",
    "How do I export my account data",
    "I want to change the region on my account",
    "My username is already taken by someone else",
    "How do I set up account recovery options",
    "I cannot link a new email to my account",
    "My account creation date is showing incorrectly",
    "How do I check who has access to my account",
    "I want to update my account's time zone",
    "I have a question about your service",
    "I need more information",
    "Where can I find your office?",
    "What are your business hours",
    "Do you offer customer support on weekends",
    "How can I contact your support team",
    "What is your company's return policy",
    "Do you have a mobile app",
    "Where can I read your terms of service",
    "How do I provide feedback about your product",
    "Do you offer discounts for students",
    "What languages does your support team speak",
    "How can I request a new feature",
    "Do you have an affiliate program",
    "What is your privacy policy",
    "How do I unsubscribe from your newsletter",
    "Do you offer a free trial",
    "What industries do you serve",
    "How long have you been in business",
    "Do you have a referral program",
    "Where can I find your press releases",
    "How do I become a partner with your company",
    "What is the best way to reach your sales team",
    "Do you offer enterprise plans",
    "How do I file a complaint",
    "What is your company mission",
    "Do you offer training or onboarding sessions",
    "How can I stay updated on new features",
    "Where can I find your community forum",
    "Do you sponsor any events",
    "What certifications does your company hold",
    "How do I request a product demo",
    "Do you have a careers page",
    "What is your company's history",
    "How can I follow you on social media",
    "Do you offer support in multiple time zones",
    "What is your average response time for inquiries",
    "How do I request a copy of your compliance documentation",
    "Do you have a status page for outages",
    "What is included in your standard plan",
    "How do I sign up for your webinar",
    "Do you offer accessibility features",
    "What is your policy on data retention",
    "How do I get in touch with a specific department",
    "Do you offer bulk purchasing options",
    "What is your company's environmental policy",
    "How do I find documentation for your product",
    "Do you have a knowledge base or help center",
    "What is the process for submitting a support ticket",
    "How do I request an accessibility accommodation",
    "Asalam",
]


categories = [
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "billing",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "technical",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "account",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
    "general",
]
