"""make ticket id in ticket status history nullable

Revision ID: 292cc189bbf8
Revises: 68fd593c16b4
Create Date: 2026-09-19 12:02:25.422293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '292cc189bbf8'
down_revision: Union[str, Sequence[str], None] = '68fd593c16b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket_status_history', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket_status_history', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
