"""added hod_id column in departments table with relationship

Revision ID: 5b4d6249be23
Revises: f630d8858bbc
Create Date: 2026-08-23 07:19:43.379479

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5b4d6249be23"
down_revision: Union[str, Sequence[str], None] = "f630d8858bbc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("departments", sa.Column("hod_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "departments", "users", ["hod_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "departments", type_="foreignkey")
    op.drop_column("departments", "hod_id")
    # ### end Alembic commands ###
