"""added relationships in department table

Revision ID: 6685287f6456
Revises: 03fe0f1fd82a
Create Date: 2026-08-25 17:37:48.478433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6685287f6456'
down_revision: Union[str, Sequence[str], None] = '03fe0f1fd82a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('hod_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'departments', 'users', ['hod_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'hod_id')
    # ### end Alembic commands ###
