"""make child rows nullable on deletion of parent row

Revision ID: 68fd593c16b4
Revises: 090bae8b7c8d
Create Date: 2026-09-19 11:46:47.962507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68fd593c16b4'
down_revision: Union[str, Sequence[str], None] = '090bae8b7c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('categories_department_id_fkey'), 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('departments_hod_id_fkey'), 'departments', type_='foreignkey')
    op.create_foreign_key(None, 'departments', 'users', ['hod_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('incoming_emails_ticket_id_fkey'), 'incoming_emails', type_='foreignkey')
    op.drop_constraint(op.f('incoming_emails_creator_id_fkey'), 'incoming_emails', type_='foreignkey')
    op.create_foreign_key(None, 'incoming_emails', 'tickets', ['ticket_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'incoming_emails', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('notifications_ticket_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('notifications_recipient_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'tickets', ['ticket_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'notifications', 'users', ['recipient_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('replies_creator_id_fkey'), 'replies', type_='foreignkey')
    op.drop_constraint(op.f('replies_ticket_id_fkey'), 'replies', type_='foreignkey')
    op.create_foreign_key(None, 'replies', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'replies', 'tickets', ['ticket_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('ticket_status_history_ticket_id_fkey'), 'ticket_status_history', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_status_history', 'tickets', ['ticket_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('tickets_department_id_fkey'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('tickets_assigned_id_fkey'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('tickets_student_id_fkey'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('tickets_category_id_fkey'), 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tickets', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tickets', 'users', ['assigned_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tickets', 'users', ['student_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('tickets_category_id_fkey'), 'tickets', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(op.f('tickets_student_id_fkey'), 'tickets', 'users', ['student_id'], ['id'])
    op.create_foreign_key(op.f('tickets_assigned_id_fkey'), 'tickets', 'users', ['assigned_id'], ['id'])
    op.create_foreign_key(op.f('tickets_department_id_fkey'), 'tickets', 'departments', ['department_id'], ['id'])
    op.drop_constraint(None, 'ticket_status_history', type_='foreignkey')
    op.create_foreign_key(op.f('ticket_status_history_ticket_id_fkey'), 'ticket_status_history', 'tickets', ['ticket_id'], ['id'])
    op.drop_constraint(None, 'replies', type_='foreignkey')
    op.drop_constraint(None, 'replies', type_='foreignkey')
    op.create_foreign_key(op.f('replies_ticket_id_fkey'), 'replies', 'tickets', ['ticket_id'], ['id'])
    op.create_foreign_key(op.f('replies_creator_id_fkey'), 'replies', 'users', ['creator_id'], ['id'])
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_recipient_id_fkey'), 'notifications', 'users', ['recipient_id'], ['id'])
    op.create_foreign_key(op.f('notifications_ticket_id_fkey'), 'notifications', 'tickets', ['ticket_id'], ['id'])
    op.drop_constraint(None, 'incoming_emails', type_='foreignkey')
    op.drop_constraint(None, 'incoming_emails', type_='foreignkey')
    op.create_foreign_key(op.f('incoming_emails_creator_id_fkey'), 'incoming_emails', 'users', ['creator_id'], ['id'])
    op.create_foreign_key(op.f('incoming_emails_ticket_id_fkey'), 'incoming_emails', 'tickets', ['ticket_id'], ['id'])
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.create_foreign_key(op.f('departments_hod_id_fkey'), 'departments', 'users', ['hod_id'], ['id'])
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key(op.f('categories_department_id_fkey'), 'categories', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###
