"""added priority column in tickets and made old_status and changed_bynullable in ticket_status_history table

Revision ID: 700447699615
Revises: cde2c9af239f
Create Date: 2026-09-08 11:37:46.528678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700447699615'
down_revision: Union[str, Sequence[str], None] = 'cde2c9af239f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket_status_history', 'old_status',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ticket_status_history', 'changed_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('tickets', sa.Column('priority', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'priority')
    op.alter_column('ticket_status_history', 'changed_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ticket_status_history', 'old_status',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
